
services:
  # Aplicação Next.js (Modo Desenvolvimento)
  app:
    env_file: 
      - .env
    container_name: sistema_nextjs
    build:
      context: ./next-app
      dockerfile: Dockerfile
    restart: always
    ports:
      - "3000:3000"
      - "5555:5555"
    volumes:
      - ./next-app:/app
      - /app/node_modules
      - /app/.next
    # Monta a URL de conexão usando as variáveis do .env
    environment:

      - PRISMA_CLI_QUERY_ENGINE_TYPE=binary
      - PRISMA_CLIENT_ENGINE_TYPE=binary # <--- ESSA LINHA É A CHAVE
      - AUTH_TRUST_HOST=true

    depends_on:
      - db
    networks:
      - sistema_net

  # Banco de Dados (Postgres 15.5 Alpine - Fixo)
  db:
    container_name: sistema_postgres
    image: postgres:15.5-alpine
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env  # Lê as variáveis do arquivo que criamos no Passo 2
    networks:
      - sistema_net

volumes:
  pgdata:

networks:
  sistema_net:
    driver: bridge